### PR TITLE
image-picker添加了对批量添加图片的支持，一次性把所有添加的图片都返回，只触发一次onChange

### PR DESCRIPTION
**Pull request by melchior-voidwolf**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [x] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/3115)

### CODE REVIEW

**Comment by Casper-MAGI** [comment]
ref：https://github.com/ant-design/ant-design-mobile/issues/2895

**Comment by ziluo** [comment]
这里引入Promise后需要check下兼容性问题，项目是否需要额外配置或直接引入polyfill文件 @melchior-voidwolf

**Comment by melchior-voidwolf** [comment]
> 这里引入Promise后需要check下兼容性问题，项目是否需要额外配置或直接引入polyfill文件 @melchior-voidwolf

antd-mobile的官方文档中已经推荐引入 Promise 的 fallback 支持的情况下，处理fallback的事情是否还需要内部处理？

**Comment by ziluo** [comment]
还是存在一定的向下兼容风险的，建议在组件文档里强调一下吧 @melchior-voidwolf

**Comment by ziluo** [comment]
+1

**Pull request merged**
