### PR TITLE
fix SearchBar 初始化时宽度超长问题

### PR DESCRIPTION
**Pull request by cc251850623**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/3081)

### CODE REVIEW

**Comment by cc251850623** [comment]
```
this.rightBtnRef.style.marginRight = `-${this.rightBtnRef
            .offsetWidth +
            (this.rightBtnInitMarginleft != null
              ? parseInt(this.rightBtnInitMarginleft, 10)
              : 0)}px`;

```
计算的时候 rightBtnRef 为块级元素，算出的marginRight长度不正确，改了ui后貌似jest测试不能通过。

**Comment by doxiaodong** [comment]
@ziluo

**Comment by likezero** [comment]
这个有超长的页面截图吗？ 在什么环境下产生的

**Comment by cc251850623** [comment]
开发环境，但是当时没做按需加载，现在想想也有可能是由于CSS加载慢了，导致的这个问题。
image

**Comment by doxiaodong** [comment]
先把 jest 的快照改了吧

**Comment by awmleer** [comment]
v2 已经不再维护了，这个 PR 先关闭了哈，如果有兴趣的话可以关注一下最新的 v5 版本～

**Pull request closed without merging**
