### PR TITLE
refactor: combine native & web ts interface

### PR DESCRIPTION
**Pull request by paranoidjk**
## typescript interface 回滚到以前的状态：即 web & native 的 props interface 使用同一个

已知的问题:

- 导致对 react-native 的强依赖
- interface 是混合起来冗余的，不准确

- - -
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1517)

### CODE REVIEW

**Comment by paranoidjk** [comment]
cc @bccsafe @yesmeck

**Comment by paranoidjk** [comment]
ref https://github.com/ant-design/ant-design-mobile/pull/1502

**Comment by paranoidjk** [comment]
@yesmeck 这个 PR 合并之后，umd dist 的 error 应该修复了，你把测试加上来吧

**Comment by bccsafe** [comment]
@paranoidjk 

不是应该去解决umd的问题吗，入口里不要去用`type.tsx`

现在回滚的考虑是什么

**Comment by paranoidjk** [comment]
@bccsafe 功能正常是高优先级，没有好的方案完全解决这个问题之前先保持混合的状态

**Pull request merged**
