### PR TITLE
fix(SearchBar): add cancelTextColor

### LINKED ISSUE #1213: Provide a variable to custom the cancel text color in Searchbar
### What problem does this feature solve?
When we custom the fill color to `brand_primary` of the Searchbar by override `search_bar_fill `, the Cancel text will be invisible in this scene. We meet this issue because the color of Cancel text is also `brand_primary` which come from the variable `color_link`. 

### What does the proposed API look like?
Provide a variable to custom the Cancel text color, for example: `search_bar_cancel_color`

### PR DESCRIPTION
**Pull request by paranoidjk**
close #1213

First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1215)

### CODE REVIEW

**Comment by silentcloud** [comment]
加公共变量是需要设计师一起评估的，感觉这个变量太小众

那个 issue，让用户自定义单个组件的样式不是很好么？

**Comment by paranoidjk** [comment]
恩，就是给你来review的，有更好的解决方案就close掉这个去那边回复一下。

不过这个文字颜色的取值也是略奇怪，为什么文字会取color_link ？

**Comment by silentcloud** [comment]
color_link 不晓得，这个估计是之前谁写的时候遗留的问题

**Comment by paranoidjk** [comment]
@afc163 https://github.com/ant-design/ant-design-mobile/blob/master/components/search-bar/style/index.tsx#L38 这行的颜色是为什么？

**Comment by afc163** [comment]
color_link 是合理的吧，这里是一个 link button，不然应该是什么？

**Pull request closed without merging**
