### PR TITLE
fix #1475 support custom keyboard confirm label

### LINKED ISSUE #1475: <InputItem type="money" />支持自定义`确认`按钮之文案
RT

### PR DESCRIPTION
**Pull request by pingan1927**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1476)

### CODE REVIEW

**Comment by paranoidjk** [comment]
考虑下localeProvider，看下picker的处理

**Comment by pingan1927** [comment]
localeProvider 后续加上，这个业务马上就要用

**Comment by paranoidjk** [comment]
业务马上就要用 这个我不觉得能作为理由，每加一feature至少要把能考虑到的尽量做好

**Comment by pingan1927** [comment]
这个加也只是在local-provider上加，而且目前只有`DatePicker`以及`Pagination`才有，跟这个PR没关系

**Comment by pingan1927** [comment]
每个PR的提交纯粹点好

**Comment by paranoidjk** [comment]
我的意思是，有内置默认文案的组件，必须考虑国际化，目前即中英文

**Comment by paranoidjk** [comment]
你要保重英文用户用localeProvider看到的文案不能是中文

**Pull request merged**
