### PR TITLE
Feature input item onsubmit

### PR DESCRIPTION
**Pull request by alwaysloseall**
Feature #2192 

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/2249)

### CODE REVIEW

**Comment by warmhug** [comment]
这个只是针对 `type='money'` 的提交按钮，直接使用 `onSubmit` 这个 `form` 元素的属性、感觉不妥。建议改为 `onMoneyTypeConfirm` 更清晰明了。
(本来这个 CustomKeyboard 不应该叫 money type 这么狭义的命名、但既然叫了、那就统一命名最好)

cc @paranoidjk @zhang740 @pingan1927

**Comment by paranoidjk** [comment]
键盘类型还会扩展的 https://github.com/ant-design/ant-design-mobile/issues/2237

包括身份证键盘，以及不带小数点的键盘

**Comment by warmhug** [comment]
那命名上就一起再考虑吧。命名一定要慎重 贴切。

**Comment by KgTong** [comment]
ref #2551

**Comment by zmayor** [comment]
@paranoidjk 请问身份证的键盘有了吗

**Comment by liuxiaoy** [comment]
这个命名和发布时候的解释 真是要坑人。我说怎么没作用，原来真没作用。

**Pull request closed without merging**
