### PR TITLE
chore(scripts/build-less-entry.js): Achieve building consistent le…

### PR DESCRIPTION
**Pull request by cisen**
…ss on any operating system by using POSIX

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

- [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
- [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1762)

### CODE REVIEW

**Comment by paranoidjk** [comment]
Thanks for your PR. Can you explain what problems you want to solve?

**Comment by cisen** [comment]
`npm run pre-publish` will generate different files like `lib/style/components.less` on different os like macos and windows. 
windows: `@import "../accordion\style\index.less";`
macos:  `@import "../accordion/style/index.less";`
Using posix can avoid this problem by https://nodejs.org/dist/latest-v8.x/docs/api/path.html。

**Comment by paranoidjk** [comment]
1. right now we won't publish package in windows pc.
2. I think we should change below two lines code, not path api.

https://github.com/ant-design/ant-design-mobile/blob/master/scripts/build-less-entry.js#L19

https://github.com/ant-design/ant-design-mobile/blob/master/scripts/build-less-entry.js#L27

**Comment by cisen** [comment]
OK，something about ant-mobile I was no very clear. I just want to make some suggestions if I found。

**Comment by paranoidjk** [comment]
cc @afc163 same problem in antd https://github.com/ant-design/ant-design/blob/master/scripts/prepub.js#L40 , only suitable for posix system

**Pull request closed without merging**
