### PR TITLE
[WIP] add platform prop to menu

### PR DESCRIPTION
**Pull request by cncolder**
Menu and SubMenu require List.Item.

This pr add platform prop to Menu and pass through to List.Item.

It seem like someone break lint. I commit this by `git commit --no-verify`.

BTW: The SSR has worked basically after this pr.

First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1200)

### CODE REVIEW

**Comment by paranoidjk** [comment]
menu 有这个 android 的水波纹效果是不是不太好？

**Comment by paranoidjk** [comment]
CI lint 没问题，应该是你本地的依赖版本不同

**Comment by cncolder** [comment]
@paranoidjk List.Item 的水波纹效果的实现方式有待商榷，默认情况下 `platform='cross'` 还会检测 `navigator.userAgent`，现阶段要想支持 SSR 就必须在服务端传入 platform。

**Comment by paranoidjk** [comment]
@cncolder 这个问题是通用的，好几个组件都有 platform 这个api，https://github.com/ant-design/ant-design-mobile/search?l=TypeScript&q=platform&type=&utf8=%E2%9C%93 如果ssr的时候服务端指定 platform 其实也不太好指定哪个。

你看看你有没有意向重构一下，`platform="cross"`的时候把真正的渲染延迟到componentDidMount之后做，就像 https://github.com/ant-design/ant-design-mobile/pull/1153 这里

**Comment by cncolder** [comment]
@paranoidjk 目前有3个组件：ListItem Modal Switch

我在想 ListItem 这个组件会用上比较普遍，会不会同一个页面出现次数太多，多一次 render 对 ListItem 的影响应该是最大的。

**Comment by paranoidjk** [comment]
@cncolder 看了下 ListItem 的实现其实也不太好，https://github.com/ant-design/ant-design-mobile/blob/master/components/list/ListItem.web.tsx#L131 这里可以去掉 isAndroid 的判断，改成默认`display: none`，那就不用在 render 里依赖 navigator 了

**Comment by cncolder** [comment]
@paranoidjk 你是说在 onClick 里加一行

```js
if (!isAndroid) coverRipleStyle.display = 'none';
```

**Comment by paranoidjk** [comment]
@cncolder 我的意思也是就始终渲染一个不可见的div，按这个方案做吧

**Pull request closed without merging**
