### PR TITLE
fix: update PickerData PropTypes

### PR DESCRIPTION
**Pull request by tesky0125**
close https://github.com/ant-design/ant-design-mobile/issues/2687

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/2688)

### CODE REVIEW

**Comment by micooz** [comment]
label 目前只接受 string 参数，该变更允许用户传入 Element，会影响该组件 `format` 参数的回调，相应的文档也要更新，请各位 Reviewer 评估这个变更的必要性。

```
| format  | 格式化选中值的函数  | (labels: string[]): any | `(labels) => { return labels.join(','); } ` |
```

**Comment by doxiaodong** [comment]
@micooz ，但是我看有些项目中其实是之前在使用 ReactNode 的，当时 是 `label: any`。然后前段时间变更为 string ，导致项目出错。

**Comment by ziluo** [comment]
@micooz @doxiaodong 我看了下代码，这里应该是因为`rmc-cascader`的`label`只支持`string`，但我看了下代码 https://github.com/react-component/m-cascader/blob/master/src/Cascader.tsx#L90，其实是支持ReactNode的，不过`format`的默认逻辑确实是没考虑ReactNode的情况

个人觉得这里最好支持ReactNode，方面业务线的个性化实现，如

image

大家可以讨论下怎么做 @KgTong @likezero @paranoidjk @warmhug

**Comment by micooz** [comment]
我也赞同支持 ReactNode

**Comment by ziluo** [comment]
这个PR先关掉，重新提到`2.3.x`吧，同时`rmc-cascader `也要做相应的改动

**Pull request closed without merging**
