### PR TITLE
Align extra text (fixing issue#2609)

### PR DESCRIPTION
**Pull request by viddamao**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [X] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [X] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [X] Rebase before creating a PR to keep commit history clear.
* [X] Add some descriptions and refer relative issues for you PR.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/2610)

### CODE REVIEW

**Comment by KgTong** [comment]
没有复现，能提供下复现的demo吗？

**Comment by viddamao** [comment]
https://codepen.io/paranoidjk/pen/LWpaKe
react 里似乎没问题，

react-native / expo / ios还是存在

**Comment by warmhug** [comment]
react-native 是完全不同的代码，react 没问题关了这个 pr 吧。

**Comment by warmhug** [comment]
ref #2609

**Pull request closed without merging**
