### PR TITLE
Upgrade tslint

### PR DESCRIPTION
**Pull request by afc163**
- [x] Upgrade tslint and tslint-react
- [x] Add tslint-eslint-config
- [x] Auto fix some errors can be fixed.
- [x] Manually fix left errors

Someboy come and finish the last task.

### CODE REVIEW

**Comment by warmhug** [comment]
这个改动尽快合并吧？不然冲突很多

**Comment by paranoidjk** [comment]
这个我这周末处理掉。

**Comment by paranoidjk** [comment]
wait for https://github.com/palantir/tslint-react/issues/79

**Comment by paranoidjk** [comment]
TypeScript is not 100% works fine with React.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11640

**Comment by paranoidjk** [comment]
诶，本地是过的为啥ci挂了....

**Pull request merged**
