### PR TITLE
feat(Text): add Text component

### PR DESCRIPTION
**Pull request by aso1datov**
https://github.com/ant-design/ant-design-mobile/issues/6348

### CODE REVIEW

**Comment by zombieJ** [comment]
Feature branch pls. And this PR seems not visible on the preview side bar. Pls check it.

**Comment by zombieJ** [comment]
In antd, it name as Typography. Pls follow it as Typography component.

**Comment by aso1datov** [comment]
> Feature branch pls. And this PR seems not visible on the preview side bar. Pls check it.

I put the component in the experimental section

**Comment by zombieJ** [comment]
I mean this `master` which should be `feature` : )
截屏2023-09-04 15 57 18

**Comment by zombieJ** [comment]
Why change back?

截屏2023-09-11 15 02 54

**Comment by aso1datov** [comment]
> Why change back?
> 
> 截屏2023-09-11 15 02 54

A lot of changes

**Comment by zombieJ** [comment]
You can picker your commit instead : )

**Comment by zombieJ** [comment]
Hi, why close this?

**Pull request closed without merging**
