### PR TITLE
add dot to interface TabBarItemProps

### PR DESCRIPTION
**Pull request by cncolder**
This prop pass through to Tab. It's documented but missing here.

First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by cncolder** [comment]
BTW. Should TabBarProps.children be `children?: any;`?

**Comment by paranoidjk** [comment]
children相关的要整体改，需要升级ts

https://github.com/Microsoft/TypeScript/issues/13618

**Comment by paranoidjk** [comment]
ci 挂了 ，处理一下

**Comment by cncolder** [comment]
@paranoidjk 是 accordion 样式引起的问题

```diff
   <div
         aria-expanded="false"
-        class="am-accordion-header"
+        class="am-accordion-header "
         role="tab"
       >
```

**Comment by paranoidjk** [comment]
如果是符合预期的就 npm run web -- -u ，不符合预期就修改下。这里应该是snapshot不变的

**Comment by cncolder** [comment]
@paranoidjk 我本地只有一个 node@v7.9.0

直接在 master 上跑 `npm run test:web` 就有3处 FAIL，swipe-action stepper list

这3处还和 CI 上面的位置不同，CI 上的两处 FAIL 都在 accordion

**Comment by paranoidjk** [comment]
@cncolder 确认分支和代码对的前提下，重装依赖试试。另外注意是否有全局安装的 typescript 等版本不同

**Comment by paranoidjk** [comment]
稍我更新master的snapshot你再rebase下 https://github.com/react-component/collapse/pull/66

**Pull request merged**
