### PR TITLE
[WIP] bugfix: entrance

### PR DESCRIPTION
**Pull request by bccsafe**
close https://github.com/ant-design/ant-design-mobile/issues/1495

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

1. 修复item的type报错
```
[ts] JSX element type 'List.Item' does not have any construct or call signatures.
```
<del>2. 给两个入口，一个生成混合的ts类型声明(index.tsx)，一个给umd之类的打web平台的包(index.web.tsx)</del>

#1339 #1376

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1502)

### CODE REVIEW

**Comment by warmhug** [comment]
需要运行`npm run compile`并保证不出错

**Comment by bccsafe** [comment]
@warmhug 目前 `npm run compile`用的入口文件是什么，index.tsx？能不能让我指定某个文件

**Comment by paranoidjk** [comment]
@bccsafe https://github.com/ant-design/ant-design-mobile/blob/master/index.web.js

**Comment by warmhug** [comment]
ref #1495

**Comment by bccsafe** [comment]
@paranoidjk 

index.web.js
```
const req = require.context('./components', true, /^\.\/[^_][\w-]+\/style\/index\.web\.tsx?$/)
```
我看没有包含type.tsx，奇怪了，umd打包怎么会打包进去的，唯一用到type.tsx的就是`src/index.tsx`

**Comment by paranoidjk** [comment]
> const req = require.context('./components', true, /^\.\/[^_][\w-]+\/style\/index\.web\.tsx?$/)

注意你发的这一行其实是引用样式

https://github.com/ant-design/ant-design-mobile/blob/master/index.web.js#L10 这一行才是引用js，就会导致 type.tsx 被打包进去

**Comment by paranoidjk** [comment]
今天也和 @warmhug 讨论过了，一种方案是把 https://github.com/ant-design/ant-design-mobile/blob/master/index.web.js#L10 js的加载也改成和style一样用 require.context去遍历加载

**Comment by bccsafe** [comment]
哦哦我知道了

我这边原来是打算加一个index.web.tsx

index.web.js里
```
require('./components/index.web');
```

你们觉得哪个方案好呢，require.context代码量更少？以后加组件也不需要去改动

**Comment by paranoidjk** [comment]
我赞成 require.context 的方案，但要注意有些 component 是 index.web.tsx, 有些就直接是 index.tsx, 比如 picker， 因为是 web & native 统一代码的

**Comment by bccsafe** [comment]
@paranoidjk 额，如果有区别的话，这正则比较难写

要不这个版本用index.web.tsx的方案，等2.0，#1235 这个后缀名改完后，用`require.context`的方案

**Comment by paranoidjk** [comment]
这个我来处理下吧，看下目前不引起 break chang 的方案是什么

**Pull request closed without merging**
