### PR TITLE
defer check platform until visible is true

### LINKED ISSUE #1305: [SSR] Modal render 方法依赖 navigator
### What problem does this feature solve?

必须指定 platform 并且不能是 cross 才能通过服务端渲染，如果未指定 platform 则取值于 navigator.userAgent。

动态服务器端有能力指定 platform，但是像 bisheng 这样静态渲染就无能为力了。

### What does the proposed API look like?

Modal 的使用方法分两种：

1. 静态方法调用 alert/prompt/operation。
2. 当成组件使用。

对于方法1，可以不做改动，因为方法1涉及到 DOM 操作，服务端肯定无法直接调用。

对于方法2，考虑到 Modal 组件的特殊性，我认为可以排除掉用户首屏就直接显示 Modal 这种可能性，只有后续 visible 为 true 时才会显示，也就是说 Modal 只会在客户端显示。

由此我想到了一个讨巧的办法：

[components/modal/Modal.web.tsx#L88](https://github.com/ant-design/ant-design-mobile/blob/37fb7ded9826d552dc3df190d32b38b4412930be/components/modal/Modal.web.tsx#L88)

```jsx
const isAndroid = platform === 'android' ||
  (platform === 'cross' && this.props.visible && !!navigator.userAgent.match(/Android/i));
```

请 @paranoidjk @warmhug 评估。

### PR DESCRIPTION
**Pull request by cncolder**
because rc-dialog won't render until visible

this pr close #1305 

First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1307)

### CODE REVIEW

**Comment by silentcloud** [comment]
这样做的意义是什么？或者说场景？

**Comment by cncolder** [comment]
@silentcloud for SSR，假设用户不会 render 一个 `<Modal visible />`，这个改动会把 `navigator.userAgent` 推迟到客户端，详见 #1305 。

**Comment by cncolder** [comment]
为什么我们所有正则都是采用 `!!str.match(/regex/)` 而不是 `/regex/.test(str)` 这种形式，这是一种传统还是有什么性能上的好处？

**Comment by paranoidjk** [comment]
@cncolder  发现可以优化的直接提PR来修改~ http://stackoverflow.com/questions/10940137/regex-test-v-s-string-match-to-know-if-a-string-matches-a-regular-expression/10940138

**Pull request merged**
