### PR TITLE
doc(ImageUploader): some `Android` phones do not support `capture`

### PR DESCRIPTION
**Pull request by MuxinFeng**

### CODE REVIEW

**Comment by MuxinFeng** [comment]
related issue: https://github.com/ant-design/ant-design-mobile/issues/5254

**Comment by miracles1919** [comment]
加个 FAQ 吧，参考 [grid](https://mobile.ant.design/zh/components/grid)

**Review by awmleer — COMMENTED** [review]
英文文档也一起更新一下吧～

**Comment by awmleer** [comment]
@miracles1919 +1 放在 FAQ 里可能更合适一些

**Comment by MuxinFeng** [comment]
搞定啦，大佬再 cc 呢

**Review by awmleer — APPROVED** [review]

**Pull request merged**
