### PR TITLE
revert(button): rest props

### PR DESCRIPTION
**Pull request by bang88**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/2404)

### CODE REVIEW

**Comment by paranoidjk** [comment]
@bang88 rn 的用例挂了。`tnpm run test:rn`, `tnpm run test:rn -- -u` etc.

**Comment by bang88** [comment]
你方便更新一下 snap 吗，我再看 #2381

**Comment by paranoidjk** [comment]
好。你们厂在用 RN 组件吗？

**Comment by bang88** [comment]
有配合着用

**Comment by paranoidjk** [comment]
还不是 snapshot 挂了，是用例挂了 https://travis-ci.org/ant-design/ant-design-mobile/jobs/355279238

**Comment by bang88** [comment]
好 晚点我看看

**Comment by bang88** [comment]
@paranoidjk 晕了 这里不需要还原了，现在这个是对的，可以取消MR吗

```ts
//  unnecessary see line: 134
    // [
    //   'activeOpacity',
    //   'underlayColor',
    //   'onPress',
    //   'onPressIn',
    //   'onPressOut',
    //   'onShowUnderlay',
    //   'onHideUnderlay',
    // ].forEach(prop => {
    //   if (restProps.hasOwnProperty(prop)) {
    //     delete restProps[prop];
    //   }
    // });
```

**Comment by paranoidjk** [comment]
那还是还原原来的代码吧，还是不要依赖顺序的潜规则来保证正确性，不利于长期维护。你新来一个 PR? 我把这个 revert 掉。

**Comment by bang88** [comment]
不还原也可以 我取消注释的就好了。

**Pull request merged**
