### PR TITLE
Tabs support badge

### PR DESCRIPTION
**Pull request by plowsirius**
ref #1536 

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [x] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1568)

### CODE REVIEW

**Comment by silentcloud** [comment]
还是那个原则，Tabs 用到 badge 的场景比较少，所以能不能 badge 不要侵入到 index.web.tsx 里？这样无形中可以减少大小

**Comment by pingan1927** [comment]
尝试过不侵入，不行。 @plowsirius 可以再深入研究下如何
最新版我们就把这个合进来吧，2.0 可以重构下

**Comment by silentcloud** [comment]
常见的展现方式就是，标签后面跟数字，你发我的视觉那种样子，压根没见过

**Comment by pingan1927** [comment]
@silentcloud 你说的常规的即后面加数字根本行不通啊，4个tab的时候(今日20)这么短会被隐藏起来...

**Comment by pingan1927** [comment]
关于组件体积大小等问题，还是要在满足业务的前提下去优化，2.0 去掉hammerjs 可以顶好几个badge了。。。
快速合并吧，和交互讨论了其他方案，该试的办法我都试了。

**Comment by silentcloud** [comment]
cc @paranoidjk

**Comment by paranoidjk** [comment]
@plowsirius Please rebase master to solve the conflict.

**Comment by paranoidjk** [comment]
@plowsirius Commit 列表有问题，请检查下。

**Comment by pingan1927** [comment]
重发一个，这个关掉

**Comment by paranoidjk** [comment]
@pingan1927 以后尽量注意下就保持一个 PR 里面改，不然关掉之后 review 又要重来，而且讨论的上下文也丢失了 😅

**Pull request closed without merging**
