### PR TITLE
Adding onLongPress to ListItem

### PR DESCRIPTION
**Pull request by zunder**
Added functionality for listening for long press on a ListItem.

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1533)

### CODE REVIEW

**Comment by pingan1927** [comment]
仅支持rn的话，文档需要更新下

**Comment by silentcloud** [comment]
@zunder 把 web 的也加上吧  https://github.com/react-component/touchable#api

**Comment by paranoidjk** [comment]
ping @zunder

**Comment by paranoidjk** [comment]
先合掉，web 和 文档我来更新。

**Comment by stonecold123** [comment]
@paranoidjk  @silentcloud  
Does List.Item support onLongPress in 2.16?
I couldn't any mention of it in the typescript definition file.

**Comment by stonecold123** [comment]
Any progress on this?

**Comment by paranoidjk** [comment]
@stonecold123 `onLongPress ` api is removed in `antd-mobile@2`, you can use below 2 components to wrap your `List.Item` children to implement long press feature.

- you can use [rc-gesture](https://github.com/react-component/gesture#tap--press), which have `onPress`, `onPressOut` api.
- you can use [rc-touchable](https://github.com/react-component/touchable), which have `onLongPress` API

cc @silentcloud

**Pull request merged**
