### PR TITLE
refactor: upgrade omit.js, which removed object-assign deps.

### PR DESCRIPTION
**Pull request by paranoidjk**
ref https://github.com/benjycui/omit.js

ref https://github.com/ant-design/ant-design-mobile/commit/586184ea873849c47f1c8bd7f152c5949a107e1b

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1506)

### CODE REVIEW

**Comment by paranoidjk** [comment]
wait for https://github.com/benjycui/omit.js/pull/1

**Comment by benjycui** [comment]
```bash
+ omit.js@1.0.0
```

**Comment by paranoidjk** [comment]
直接1.0了？ 0.x不是没必要升major么？

**Comment by benjycui** [comment]
> 直接1.0了？ 0.x不是没必要升major么？

这库已经稳定了， 1.0 能保证 Badge 的颜色

image

**Pull request merged**
