### PR TITLE
fix marginLeft

### PR DESCRIPTION
**Pull request by int2d**
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/2260)

### CODE REVIEW

**Comment by paranoidjk** [comment]
Why? What is this for?

**Comment by silentcloud** [comment]
OK， 没问题，外边距交给用户自己处理

**Comment by silentcloud** [comment]
更新一下 ci

**Comment by paranoidjk** [comment]
@int2d `npm run test:rn -- -u`

**Pull request merged**
