### PR TITLE
feat: support customizable arrow-size

### PR DESCRIPTION
**Pull request by cbbfcd**
scenes where the display of arrows needs to be overridden, so that the size can be changed with `-arrow-size`.

### CODE REVIEW

**Comment by miracles1919** [comment]
when I try to set `--arrow-size: 12px;`

image

**Comment by cbbfcd** [comment]
@miracles1919 thx to reply~

`svg` should keep the same aspect ratio, it works fine now.
but I'm starting to wonder about the cost effectiveness of this, 
but there are indeed scenes that need to override the size of the arrows. 😂

**Comment by zombieJ** [comment]
Is this possible to use css calc instead getComputedStyle ?

**Comment by cbbfcd** [comment]
> Is this possible to use css calc instead getComputedStyle ?

let me try, better suggestion, thx~

**Comment by zombieJ** [comment]
Could you help to move this PR to feature branch base?

**Comment by cbbfcd** [comment]
> Could you help to move this PR to feature branch base?

@zombieJ okk~

**Pull request closed without merging**
