### PR TITLE
add doc for create-react(-native)-app, ref #1362

### PR DESCRIPTION
**Pull request by silentcloud**
---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1395)

### CODE REVIEW

**Comment by silentcloud** [comment]
@paranoidjk

**Comment by paranoidjk** [comment]
close #1362 

@silentcloud what about push your code to antd-mobile-samples, and give a link in doc.
like https://ant.design/docs/react/use-with-create-react-app

**Comment by paranoidjk** [comment]
@silentcloud eslint 挂了，应该是升级了的问题，我来修复下。 https://github.com/ant-design/ant-design/commit/fd625ef1a0aa12a901b17557a0cf72f041bf77d8

**Comment by silentcloud** [comment]
ok, I will push my code to antd-mobile-samples later

**Pull request merged**
