### PR TITLE
input-item: Add a clear button for android platform

### PR DESCRIPTION
**Pull request by alwaysloseall**
#2288 
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/2358)

### CODE REVIEW

**Comment by paranoidjk** [comment]
Does clean icon is a Android Design Guide or something? Why only add in android?

**Comment by paranoidjk** [comment]
cc @silentcloud

**Comment by alwaysloseall** [comment]
@paranoidjk the clean icon is gotten from antd-mobile`s assets image.only added in android, cuz ios already have a clear button in input-item

**Comment by warmhug** [comment]
close #2288

**Pull request merged**
