### PR TITLE
fix(button): bind event on touchable container, not inner component

### PR DESCRIPTION
**Pull request by paranoidjk**
First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by paranoidjk** [comment]
关联issue， 内部 `#408`

**Comment by warmhug** [comment]
其他用到 Touchable 的都是把 onClick 绑在touchable里面的元素，看看其他有没问题？

**Comment by paranoidjk** [comment]
@warmhug 只要具有`props.onClick`和`props.disabled`的功能，然后用户在`props.onClick`里面设置`disabled=true`, 就会出现这个结果，即`active`和`disabled`的`css class`同时留下来了，我刚看了下，比如`List.Item`就有，我一起修复下

**Comment by paranoidjk** [comment]
PopOverItem 也有问题，已fix

**Comment by paranoidjk** [comment]
`segemented-control`也已经fix

`action-sheet` `image-picker` `modal`也用了`rc-touchable`，但没有`disabled`和`onCllick`结合用的场景，不做修改

**Comment by silentcloud** [comment]
验证没问题就合吧

**Pull request merged**
