### PR TITLE
change style same as antd

### PR DESCRIPTION
**Pull request by rubyinwater**
First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by saiyagg** [comment]
修改组件页面左侧分类样式， 和 http://ant.design 组件页面左侧导航样式保持一致

之前为：

image

修改成：

image

**Comment by silentcloud** [comment]
@afc163 @benjycui 看哈？

**Comment by afc163** [comment]
Basic 就行了，Basic Components 略啰嗦。

**Comment by benjycui** [comment]
只是改了分类，网站方面没问题的。

**Comment by benjycui** [comment]
另外可以在这里 https://github.com/ant-design/ant-design-mobile/blob/master/site/theme/index.js#L4-L13 调整分类的顺序，可以参考 antd 的配置。

**Comment by warmhug** [comment]
即将引起冲突，先合并，有需要再拉分支改

**Comment by benjycui** [comment]
> 即将引起冲突，先合并，有需要再拉分支改

杀人预告既视感。

**Pull request merged**
