### PR TITLE
修复Steps组件连接线无法自适应高度问题

### PR DESCRIPTION
**Pull request by linhanyang**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1922)

### CODE REVIEW

**Comment by linhanyang** [comment]
@paranoidjk

**Comment by silentcloud** [comment]
@linhanyang 你 PR 的分支是不是错了，看起来你是想修复 1.x

**Comment by linhanyang** [comment]
我看了下2.x也有这个问题，希望2.x也把这个问题也修复以下。

**Comment by linhanyang** [comment]
先别合并了，我重新PR一份吧。

**Pull request closed without merging**
