### PR TITLE
【WIP】upgrade svg-sprite-loader to 2.0.6

### PR DESCRIPTION
**Pull request by Meeeeow**
Updated by @paranoidjk
https://github.com/ant-design/ant-design-mobile/commit/38e4ae2981807af30841bfe2b44bde413728f9ab?diff=unified
已经更新了文档，暂时先别升级，这个升级方案要仔细评估能否向下兼容，业务有太多依赖

```diff
-npm install svg-sprite-loader -D
+npm install svg-sprite-loader@0.3.1 -D
```

这个升级要仔细考虑， 如 https://github.com/ant-design/ant-design-mobile/issues/1283 所说

- antd-mobile 错误的把 svg-sprite-loader 作为了 devDeps（事实上也没法控制用户的loader版本）
- https://mobile.ant.design/components/icon#如何使用-(WEB-版) 这里的官方文档又没有指定版本
- 所以目前 svg-sprite-loader 的版本其实是在用户端控制的

我们要升级，必须要能做到新老配置都兼容

close https://github.com/ant-design/ant-design-mobile/issues/1283

- - -
First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style. (Error: spawn node ENOENT)
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/1311)

### CODE REVIEW

**Comment by Meeeeow** [comment]
I'm not sure what happened 😢

**Comment by paranoidjk** [comment]
这个升级要仔细考虑， 如 https://github.com/ant-design/ant-design-mobile/issues/1283 所说

- antd-mobile 错误的把 svg-sprite-loader 作为了 devDeps
- https://mobile.ant.design/components/icon#如何使用-(WEB-版) 这里的官方文档又没有指定版本
- 所以目前 svg-sprite-loader 的版本其实是在用户端控制的

我们要升级，必须要能做到新老配置都兼容

**Comment by paranoidjk** [comment]
目前最保险的方案应该是文档改成 `npm install svg-sprite-loader@0.3.1 -D`

cc @warmhug

**Comment by paranoidjk** [comment]
@Meeeeow antd-mobile 已经进入 2.x 的开发期，分支如下：

https://github.com/ant-design/ant-design-mobile/tree/master -> 2.x
https://github.com/ant-design/ant-design-mobile/tree/1.x -> 1.x

请解决冲突。:smile

**Comment by paranoidjk** [comment]
Thx for you pr, going to close since we decided to split svg icon to a single npm package in antd-mobile@2.0

**Pull request closed without merging**
