### PR TITLE
add focus support for TextareaItem

### PR DESCRIPTION
**Pull request by pingan1927**
First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by afc163** [comment]
focused 怎么能作为属性，两个组件同时指定了 focused 怎么办？

**Comment by pingan1927** [comment]
同一个时刻只有一个会生效

**Comment by afc163** [comment]
这种属性不合理的，只能有类似原生 input 的 autoFocus。

**Comment by warmhug** [comment]
image

这是什么命令做到的？把别的 commit 也搞进来、怎么 review

**Pull request merged**
