### PR TITLE
优化autoFoucs

### PR DESCRIPTION
**Pull request by pingan1927**
First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by paranoidjk** [comment]
commit 列表绝对有问题...

**Comment by pingan1927** [comment]
怪 重来

**Comment by paranoidjk** [comment]
git reset {commit hash id} --hard && git push -f

**Comment by paranoidjk** [comment]
或者关掉也行

**Pull request closed without merging**
