### PR TITLE
rename wrapOnTouchStart to onWrapTouchStart

### PR DESCRIPTION
**Pull request by avalanche1**
Makes much more sense grammar-wise

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/2535)

### CODE REVIEW

**Comment by warmhug** [comment]
Need to be fully revised.
https://github.com/ant-design/ant-design-mobile/search?utf8=%E2%9C%93&q=onWrapTouchStart&type=

**Comment by avalanche1** [comment]
I could do it if you're ok with the API change

**Comment by warmhug** [comment]
Did this cause api change?

**Comment by avalanche1** [comment]
Well, I guess renaming an component property is a breaking change..

**Comment by warmhug** [comment]
So, close this pr?

**Comment by warmhug** [comment]
Thanks pr, we may not need modify it.

**Pull request closed without merging**
